### ISSUE TITLE
Doorbell without homebase

### ISSUE THREAD

**Issue by DanPatten** [JanLoebel/eufy-node-client#13]
Trying to do a lookup service on the wired doorbell directly. Does this work without the homebase?

const address = await lookupService.lookup('192.168.0.155');

This just times out on port 32108.

**Comment by JanLoebel** [comment]
Sorry, I don't know if there is a direct way to communicate with the devices without the homebase. Please check the examples and the FAQ there:

https://github.com/JanLoebel/eufy-node-client-examples
