### ISSUE TITLE
help starting node.js

### ISSUE THREAD

**Issue by xraywinedrinker** [JanLoebel/eufy-node-client#26]
I have installed your node and can run the p2p local file from the terminal to change my security mode but wanted to find out how to run it from webcore using a get request? I'd like to incorporate the mode changes with smartthings.
thanks

**Comment by JanLoebel** [comment]
@xraywinedrinker Sorry, this project is just a client, an application like something for smartthings must be implemented in another project and could use this client for that. Checkout https://github.com/bropat/ioBroker.eufy-security he has done that for the ioBroker.

**Comment by xraywinedrinker** [comment]
Thanks for responding. I have been able to fire the node in flask from the p2p but as you have noted in the open issues. I can’t send a mode change request after the first request opened the connection. Hopefully the request can be disconnected.

Cheers,

Michelle
